### ISSUE TITLE
The next letter is getting duplicated

### ISSUE THREAD

**Issue by blueedgetechno** [RedEdge967/Keyboard-Hero#2]
I don't know whether or not this is intentional but the next letter is sometimes is getting chosen same as previous one.

Like If sometimes the sequence can be A B C D D E ... which contains same consecutive letters.

**Comment by RedEdge967** [comment]
Yes. It is made to happen like that. because when the same key is shown and you are hoping to touch a another key not the same key, so this will help people move their fingers quickly to the key. I also used this to improve my typing. it may repeat the same key 3 or 4 times also.

**Comment by RedEdge967** [comment]
so if you get the idea can I close this issue?
